### ISSUE TITLE
arviz 0.16.0 pyhd8ed1ab_0 is broken (for Python < 3.9)

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/arviz-feedstock#43]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

`arviz=0.16.0=pyhd8ed1ab_0` was uploaded without the right version pins. This was corrected in #41.

Can the `arviz=0.16.0=pyhd8ed1ab_0` build be marked broken so that it doesn't land in Python 3.8 environments? I'm happy to do the admin to get that marked, so am just looking for an OK from the maintainers here.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by OriolAbril** [comment]
That would be great yes. I didn't know how to do it. I will review the PR, thanks!
